### ISSUE TITLE
Release version 0.1.1

### ISSUE THREAD

**Issue by LordGaav** [innoteq/devpi-slack#1]
The current version on Pypi is out of date and does not work with devpi-server >= 4.

You should release a new version on Pypi.

**Comment by max-arnold** [comment]
Here you go!
https://pypi.python.org/pypi/devpi-slack

**Comment by LordGaav** [comment]
:+1:

**Comment by max-arnold** [comment]
With devpi it is very easy to forget to upload something to pypi :)
