### ISSUE TITLE
Does this plugin still work?

### ISSUE THREAD

**Issue by LordGaav** [innoteq/devpi-slack#7]
I'm using these versions of devpi and devpi-slack:

  devpi-server-6.3.1
  devpi-slack-0.1.3
  devpi-web-4.0.8

Does this plugin still work with the latest version of devpi? I can see a log message that the plugin is found and loaded, but no message is sent to Slack on upload.

I'm assuming that the plugin exits on [this line](https://github.com/innoteq/devpi-slack/blob/f143bd9b4e636b77e421f75871b71d57bbfa59d8/devpi_slack/main.py#L22), because no message is logged that a message was sent to Slack or that any error was received. This means that somehow the index config was not read correctly, because there is a `slack_hook` variable present.

**Comment by max-arnold** [comment]
Apparently, the plugin API in Devpi has changed and devpi-slack became outdated.

I no longer have access to this repository, so I made a fix in my personal fork. Please try the latest master branch directly from Git and let me know whether it works for you: https://github.com/max-arnold/devpi-slack/commits/master

If you succeed, I'll upload the updated package to PyPI.

**Comment by LordGaav** [comment]
Having installed the Python package directly from Git, I can confirm that the Slack plugin works again.

**Comment by max-arnold** [comment]
Uploaded version 0.1.4 to PyPI: https://pypi.org/project/devpi-slack/

**Comment by max-arnold** [comment]
@LordGaav Could you please close the issue? I can't do that because I'm not a member

**Comment by LordGaav** [comment]
Done, thanks
